### ISSUE TITLE
Bewaartermijnen checken

### ISSUE THREAD

**Issue by baszoetekouw** [SURFscz/SRAM-generic#10]
We moeten zorgen dat de bewaartermijn die we in [ons privacy statement](https://wiki.surfnet.nl/display/SRAM/Privacy+Policy) afgeven, juist zijn. Dat kan door die bewaartermijn te realiseren zoals genoemd in het privacy statement, of door dat privacy statement aan te passen.

**Comment by arnoutt** [comment]
Uit de privacy policy:
- 12 maanden inactiviteit = mail, 3 maanden geen reactie / activiteit = verwijderen user profile data
- CO verwijderen = verzoek, moet binnen 8 weken afgehandeld worden'
- CO inactivtiet: 12 maanden geen activiteit = mail naar CO admin, 3 maanden geen reactie / activiteit = verwijderen user profile data
- Na beëindiging contract: max 18 maanden bewaartermijn voor contactgegevens org + admin(s)
- Idem voor SPs
- Log data = 6 maanden bewaard

**Comment by baszoetekouw** [comment]
Behalve de suspension van users (zie #312) is dit allemaal ok.
