### ISSUE TITLE
OPA bekijken

### ISSUE THREAD

**Issue by baszoetekouw** [SURFscz/SRAM-generic#22]
OPA ziet eruit als een leuke component die we misschien in of bij SRAM zouden kunnen gebruiken. https://www.openpolicyagent.org/
We moeten eens proberen het aan de praat te krijgen om te kijken wat het precies doet.

**Comment by mrvanes** [comment]
https://confluence.ia.surf.nl/pages/viewpage.action?pageId=107891684
