### ISSUE TITLE
Pam-weblogin demo-omgeving

### ISSUE THREAD

**Issue by baszoetekouw** [SURFscz/SRAM-generic#5]
Idealiter hebben we een standaard sandbox container waar zowel de ldap sync als pam-websso in is geinstalleerd.  Je hoeft dan alleen een paar vars (pam-websso url en token, ldap credentials) te zetten en de docker regelt verder alles zelf.

Is zoiets haalbaar?

**Comment by mrvanes** [comment]
Werkt, maar het laat zich niet heel makkelijk kneden naar bijvoorbeeld SRAM-TST op basis van alleen de .env file.

**Comment by baszoetekouw** [comment]
Deze doe t het nu idd goed!
