### ISSUE TITLE
test-rp integreren in demo-sp.sram.surf.nl

### ISSUE THREAD

**Issue by baszoetekouw** [SURFscz/SRAM-generic#7]
Martin heeft Test RP gemaakt: https://sram-rp.pt-76.utr.surfcloud.nl/. Permanent maken?  → integreren in demo-sp.sram.surf.nl (ap)

**Comment by baszoetekouw** [comment]
goede gelegenheid om metene de UI van demo-sp aan te pakken

**Comment by mrvanes** [comment]
https://github.com/SURFscz/SRAM-deploy/commit/4d55a2f16dcf6ebc7366992fd543534e02a540b6
